### ISSUE TITLE
Improvement Meta-list v2

### ISSUE THREAD

**Issue by Gnimuc** [JuliaInterop/Clang.jl#228]
### Up-for-grabs
- [x] extract docstrings from comments: #195 
- [x] support `vararg` functions: #146 #17 (for Julia 1.5+)
  * https://github.com/JuliaLang/julia/pull/32748
  * https://github.com/JuliaLang/julia/issues/32758
  * https://github.com/JuliaLang/julia/pull/32800
- [x] better support for bitfield struct(see https://github.com/JuliaInterop/Clang.jl/issues/228#issuecomment-813511951)
- [x] support documentation dumping
- [x] add more helper functions for libclang C API: #126 
- [x] missing argument names for typedef'd args: #136 

### Done
- [x] support non-literal macro definitions: #168 #103 #266 #255
- [x] struct/union improvements: `__attribute__` #224 
- [x] handle forward-decls: https://github.com/JuliaInterop/Clang.jl/issues/240#issuecomment-546788528
- [x] map missing C types: ~~#206~~ #168 #81 (the ultimate solution would be to make a package like rust's [libc](https://github.com/rust-lang/libc))

### Long-shot Issues
- wrapper generator for C++: #132 (maybe for CxxWrap.jl)
- support `va_list` ? (not sure about the use-cases) 
- handle macro/function definitions in a generic way: #267

**Comment by ViralBShah** [comment]
Do we have support for `_Generic`?

Came up in https://discourse.julialang.org/t/clang-jl-wrapper-generation-warnings-missing-parts/34093/7?u=viralbshah and https://twitter.com/DocSparse/status/1345479244466544641

**Comment by Gnimuc** [comment]
Handing function-like macros with libclang is not easy because macros are processed by the preprocessor, there is actually no much information left in the cursors(AST). One needs to tokenize and retrieve the source code of the macro definition and then manually parse the raw string to do something meaningful. 

As macro definitions may contain any valid C code, to support function-like macros in a generic way is equivalent to implement a C-to-Julia source code translator. But it looks like C11's Generic selection macros have a simple fixed pattern which, I think, could be supported in Clang.jl, I'm going to submit a PR later on.

**Comment by jpsamaroo** [comment]
Another item for the list: C bitfields. Even though [according to Linus Torvalds](https://yarchive.net/comp/linux/bitfields.html) bitfields are usually a terrible idea, they're still used in the Linux kernel's structs, which I need to be able to manipulate in BPFnative.jl.

Even though the layout of such structs are implementation-dependent, I thing we should *try* to implement support for these, using the host architecture as a hint as to the layout. We can use the `Base.getproperty` approach to generate accessors that implement the necessary bit-twiddling operations.

**Comment by Gnimuc** [comment]
@jpsamaroo Could you elaborate more about how to implement the necessary bit-twiddling operations? libclang can tell `the offset of the bitfield` and the `bitfield width`.

**Comment by jpsamaroo** [comment]
For a `setproperty!`: Based on the size of the bitfield, for each byte that the bitfield is a component of, you'd read the byte, left-shift the user-supplied value according to the bitfield's offset into that byte and the length of the bitfield, mask out (with bitwise `and`) the relevant portion of the byte with zeros, bitwise `or` the shifted supplied value with the read byte, and write the updated byte back into the struct.

**Comment by melonedo** [comment]
> 
> 
> For a `setproperty!`: Based on the size of the bitfield, for each byte that the bitfield is a component of, you'd read the byte, left-shift the user-supplied value according to the bitfield's offset into that byte and the length of the bitfield, mask out (with bitwise `and`) the relevant portion of the byte with zeros, bitwise `or` the shifted supplied value with the read byte, and write the updated byte back into the struct.

I am afraid the biggest issue is not bit manipulation but the internal layout. The C language does not define a standard layout for bit fields, unless explicit alignment directives (like `pack(1)` are used. For example:
```c
struct S {
    unsigned b1 : 30;
    unsigned b2 : 4;
    unsigned b3 : 30;
};
```
how much space does S need? We have to figure out these implementation defined behavior to ensure bit fields are handled correctly.

**Comment by Gnimuc** [comment]
That info can be queried from libclang, specifically, [`clang_Type_getSizeOf`](https://github.com/JuliaInterop/Clang.jl/blob/master/src/generator/codegen.jl#L508) & [`clang_Type_getOffsetOf`](https://github.com/JuliaInterop/Clang.jl/blob/master/src/generator/codegen.jl#L238).

**Comment by melonedo** [comment]
> That info can be queried from libclang, specifically, [`clang_Type_getSizeOf`](https://github.com/JuliaInterop/Clang.jl/blob/master/src/generator/codegen.jl#L508) & [`clang_Type_getOffsetOf`](https://github.com/JuliaInterop/Clang.jl/blob/master/src/generator/codegen.jl#L238).

Thanks! I didn't expect it to return offset in bits instead of bytes. However, as this information is only from Clang, other compilers might have different implementation. Anyway, having them is a good starting ground.

**Comment by Gnimuc** [comment]
> However, as this information is only from Clang, other compilers might have different implementation.

Clang should be ABI compatible with gcc(at least that's the goal). As this package is mainly for generating static bindings for Julia JLL packages where only mingw/gcc/clang is used in the build environment, so it's ok to make such an assumption. 

BTW, [this](https://github.com/llvm/llvm-project/blob/9964b0ef828b685dc575a50f75bb1780b84b95c8/clang/lib/AST/RecordLayoutBuilder.cpp#L1554-L1561) is the implementation used in Clang, which may serve as a good reference for the impl of `getproperty`/`setproperty!`.

**Comment by Gnimuc** [comment]
Well... I just give up reading [gcc's implementation](https://github.com/gcc-mirror/gcc/blob/master/gcc/stor-layout.c) to check whether it's compatible with Clang's or not.
