### ISSUE TITLE
Improvements meta-list

### ISSUE THREAD

**Issue by ihnorton** [JuliaInterop/Clang.jl#33]
- [ ] tests
- [ ] better dependency resolution (emit types after the entire pass)
- [x] integrate new struct improvements
- [ ]  support const array definitions

**Comment by Gnimuc** [comment]
I think these features have already been implemented and I've updated a new improvements list in #228, so close this.
